### ISSUE TITLE
Cannot load default config file

### ISSUE THREAD

**Issue by lobingera** [JuliaGraphics/Fontconfig.jl#13]
Reported in https://github.com/GiovineItalia/Compose.jl/issues/230: Configuration problems with Windows 10.

**Comment by bjarthur** [comment]
this is a problem with OSX-sierra as well

**Comment by bjarthur** [comment]
i believe the problem is that FontConfig is hard-coded to use

```
    @static if is_apple()
        ENV["FONTCONFIG_FILE"] = joinpath(Homebrew.prefix(), "etc", "fonts", "fonts.conf")
    end
```

if the system copy of homebrew (as opposed to HomeBrew.jl) has installed fontconfig, then the right place to find `fonts.conf` is in `/usr/local/etc/fonts/`

**Comment by lobingera** [comment]
I cannot test this (as i have no OSX available) but it seems reasonable.

**Comment by staticfloat** [comment]
Hmmm, yes that's a good point.  We should wrap that `ENV[]` setting within an `isfile()` so that this only happens if that file actually exists.
